project_id = "ucjyobemrxqfcoopkcgb"

[functions.chat]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.backblaze-upload-url]
verify_jwt = true

[functions.instagram-insights]
verify_jwt = false
